POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFudXJhZ3JveTExIiwiaWQiOiI1ZmJlYzk2YzU5NmFjODA5YWJkZDQyNmUiLCJpYXQiOjE2MDYzNDA0MzB9.Kei_XJxwp-Nx3WSmtQ6zSMJO86cy5WO9Tr-aCjMtuZs

{
  "title": "My Final Blog",
  "likes": 3
}